language: cpp
dist: bionic

matrix:
  include:
    - os: linux
      env:
        - MATRIX_EVAL=""
        - COMPILER="g++"
    - os: linux
      env:
        - MATRIX_EVAL=""
        - COMPILER="clang++"
    - os: osx
      osx_image: xcode11.7
      env:
        - MATRIX_EVAL="brew install gcc@7"
        - COMPILER="g++-7"
    - os: osx
      osx_image: xcode11.7
      env:
        - MATRIX_EVAL=""
        - COMPILER="clang++"

before_install:
  - eval "${MATRIX_EVAL}"

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_CXX_COMPILER=${COMPILER}
- make
- ./test64