language: cpp

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          sources: 
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: COMPILER=g++-7
    - os: linux
      compiler: clang
      addons:
        apt:
          packages:
            - clang++-7
      env: COMPILER=clang++-7.0
    - os: osx
      compiler: gcc
      addons:
        brew:
          packages:
            - gcc@7
      env: COMPILER=g++-7
    - os: osx
      compiler: clang
      addons:
        brew:
          packages:
            - llvm@7
      env: COMPILER=/usr/local/bin/clang++-7.0

script:
- mkdir build
- cd build
- cmake .. -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_EXE_LINKER_FLAGS=-fuse-ld=gold
- make
- ./test64