language: cpp

compiler:
- gcc
- clang

os:
- linux
- osx

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - cmake

script:
- mkdir build
- cd build
- cmake ..
- make
- ./test64